version: "3"

services: 
    web:
        container_name: node_app
        restart: always
        build: .
        ports: 
            - "5000:3000"
        links:
             - mongo
        
    mongo:
        container_name:  mongo_db
        image: mongo
        ports: 
            - "27018:27017"     